version: '3.8'

services:
  hogword-api:
    build: .
    container_name: hogword-api
    ports:
      - "1234:80"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    restart: always
